name: thisdatedoesnotexist
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  appinio_swiper: ^2.1.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.0
  connectivity_plus: ^5.0.2
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  feedback: ^3.0.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  flutter_modular: ^6.3.2
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  mask_text_input_formatter: ^2.7.0
  mobx: ^2.2.1
  onesignal_flutter: ^5.0.4
  path_provider: ^2.1.1
  sentry_flutter: ^7.12.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  timeago: ^3.6.0
  web_socket_channel: ^2.4.0
  image_cropper: ^5.0.1
  skeletonizer: ^1.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  mobx_codegen: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
